/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JsSidebar {
        "address": string;
        "heading": string;
        "onopenhandler": () => void;
        "phone": string;
        "text": string;
    }
}
declare global {
    interface HTMLJsSidebarElement extends Components.JsSidebar, HTMLStencilElement {
    }
    var HTMLJsSidebarElement: {
        prototype: HTMLJsSidebarElement;
        new (): HTMLJsSidebarElement;
    };
    interface HTMLElementTagNameMap {
        "js-sidebar": HTMLJsSidebarElement;
    }
}
declare namespace LocalJSX {
    interface JsSidebar {
        "address"?: string;
        "heading"?: string;
        "phone"?: string;
        "text"?: string;
    }
    interface IntrinsicElements {
        "js-sidebar": JsSidebar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "js-sidebar": LocalJSX.JsSidebar & JSXBase.HTMLAttributes<HTMLJsSidebarElement>;
        }
    }
}
